name: Unit Tests

on:
  push:
    branches:
      - main
  pull_request:
    branches:
      - main
    
jobs:
  build:
    name: Test on ubuntu
    runs-on: ubuntu-latest
    
    steps:
      - name: Check out 
        uses: actions/checkout@v4
          
      - name: Set up Java 21
        uses: actions/setup-java@v4
        with:
          distribution: 'temurin'
          java-version: '21'
          cache: 'maven'

      - name: Build with Maven
        run: mvn --batch-mode --update-snapshots verify    

    
  


